package harness_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/jimbery/receipt/internal/classify"
	"github.com/jimbery/receipt/internal/emailtypes"
	"github.com/jimbery/receipt/internal/mail"
)

// Hold-out fixtures are not generated by LoadFrozenCorpus — they guard against
// template memorisation on the synthetic 560-message corpus.
func TestHoldoutFixtures_Classifier(t *testing.T) {
	root := filepath.Join("..", "..", "..", "test", "testdata", "email", "holdout")
	cases := []struct {
		file  string
		label emailtypes.DocumentKind
	}{
		{"marketing-loyalty-voucher.txt", emailtypes.KindMarketing},
		{"currys-click-collect.txt", emailtypes.KindPurchaseReceipt},
		{"dpd-delivered-no-total.txt", emailtypes.KindDispatchNotice},
		{"barclays-statement-ready.txt", emailtypes.KindStatement},
	}
	clf := classify.New()
	for _, tc := range cases {
		data, err := os.ReadFile(filepath.Join(root, tc.file))
		if err != nil {
			t.Fatal(err)
		}
		msg, err := mail.ParseRFC822(data, tc.file, "holdout")
		if err != nil {
			t.Fatalf("%s: parse: %v", tc.file, err)
		}
		got := clf.Classify(msg)
		if got != tc.label {
			t.Fatalf("%s: got %s want %s", tc.file, got, tc.label)
		}
	}
}
